# Change this if you are using on-premise brood
store_url: https://packages.enthought.com

# Custom list of repositories used to resolve packages and runtimes
repositories:
- enthought/free
- enthought/commercial

# Directory to use to cache downloaded files.
files_cache: ~/.cached_eggs
